SRCS = srcs/ft_putchar.c srcs/ft_putstr.c srcs/ft_strcmp.c srcs/ft_strlen.c srcs/ft_swap.c
OBJECTS = $(SRCS:.c=.o)
INCLUDES = includes
NAME = libft.a
LIBC = ar rc
LIBR = ranlib
CC = CC
RM = rm -f
CFLAGS = -Wall -Werror -Wextra
